LEN_CACHE_ID: int = 4
LEN_COLLOCATED: int = 1
LEN_CURSOR_PAGE_SIZE: int = 4
LEN_DISTRIBUTED_JOIN: int = 1
LEN_ENFORCE_JOIN_ORDER: int = 1
LEN_INCLUDE_FIELD_NAMES: int = 1
LEN_LAZY: int = 1
LEN_LOCAL_QUERY: int = 1
LEN_MAX_ROWS: int = 4
LEN_QUERY_ARG_COUNT: int = 4
LEN_REPLICATED_ONLY: int = 1
LEN_STATEMENT_TYPE: int = 1
LEN_TIMEOUT: int = 8

QUERY_SQL: int = 2002
QUERY_SQL_CURSOR_GET_PAGE: int = 2003
QUERY_SQL_FIELDS: int = 2004
